apiVersion: v1
kind: Namespace
metadata:
  name: getteacher-app
  labels:
    environment: release
---
apiVersion: v1
kind: Service
metadata:
  name: getteacher-service
  namespace: getteacher-app
spec:
  selector:
    app: getteacher-app
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: getteacher-app
  namespace: getteacher-app
spec:
  selector:
    matchLabels:
      app: getteacher-app
  template:
    metadata:
      labels:
        app: getteacher-app
    spec:
      containers:
      - name: getteacher-container
        image: getteacher:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80
        env:
        - name: ASPNETCORE_URLS
          value: "http://+:80"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Release"
        - name: REDIS_CONN_IP
          value: "redis-service:6379"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: getteacher-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: getteacher-app
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
  type: ClusterIP
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: getteacher-hpa
  namespace: getteacher-app
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: getteacher-app
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 75
